services:
  find-a-friend-api:
    container_name: find-a-friend-api
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment: 
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - find_a_friend_data:/bitnami/postgresql
volumes:
  find_a_friend_data: