services:
  find-a-friend-api:
    container_name: find-a-friend-api
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findfriend
    volumes:
      - find_a_friend_data:/bitnami/postgresql
volumes:
  find_a_friend_data: